// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EdenWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EdenWebAPI.Models.Configurations
{
    public partial class HistoryConfiguration : IEntityTypeConfiguration<History>
    {
        public void Configure(EntityTypeBuilder<History> entity)
        {
            entity.Property(e => e.HistoryId)
                .ValueGeneratedNever()
                .HasColumnName("HistoryID");

            entity.Property(e => e.ClosingDay).HasColumnType("date");

            entity.HasOne(d => d.OrderNoNavigation)
                .WithMany(p => p.History)
                .HasForeignKey(d => d.OrderNo)
                .HasConstraintName("FK__History__OrderNo__29572725");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<History> entity);
    }
}
