// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EdenWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace EdenWebAPI.Models.Configurations
{
    public partial class OrdersConfiguration : IEntityTypeConfiguration<Orders>
    {
        public void Configure(EntityTypeBuilder<Orders> entity)
        {
            entity.HasKey(e => e.OrderId)
                .HasName("PK__Orders__C3905BAFB99AF57A");

            entity.Property(e => e.OrderId)
                .ValueGeneratedNever()
                .HasColumnName("OrderID");

            entity.Property(e => e.Tip).HasColumnType("money");

            entity.Property(e => e.TotalPrice).HasColumnType("money");

            entity.HasOne(d => d.DrinksNavigation)
                .WithMany(p => p.Orders)
                .HasForeignKey(d => d.Drinks)
                .HasConstraintName("FK__Orders__Drinks__267ABA7A");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Orders> entity);
    }
}
