// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EdenWebAPI.Models
{
    public partial class Beverages
    {
        public Beverages()
        {
            Orders = new HashSet<Orders>();
        }

        public int DrinkId { get; set; }
        public string Drink { get; set; }
        public decimal? Price { get; set; }
        public bool? Extra { get; set; }

        public virtual ICollection<Orders> Orders { get; set; }
    }
}