// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EdenWebAPI.Models.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable disable

namespace EdenWebAPI.Models
{
    public partial class EdenDBContext : DbContext
    {
        public EdenDBContext()
        {
        }

        public EdenDBContext(DbContextOptions<EdenDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Beverages> Beverages { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.BeveragesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.HistoryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.OrdersConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
