// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EdenWebAPI.Models
{
    public partial class History
    {
        public int HistoryId { get; set; }
        public DateTime? ClosingDay { get; set; }
        public int? OrderNo { get; set; }

        public virtual Orders OrderNoNavigation { get; set; }
    }
}