// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EdenWebAPI.Models
{
    public partial class Orders
    {
        public Orders()
        {
            History = new HashSet<History>();
        }

        public int OrderId { get; set; }
        public int? Drinks { get; set; }
        public int? Quantity { get; set; }
        public decimal? Tip { get; set; }
        public decimal? TotalPrice { get; set; }

        public virtual Beverages DrinksNavigation { get; set; }
        public virtual ICollection<History> History { get; set; }
    }
}